* wtd.server

  Server providing RPC API for use by wtd.el and other potential WTD
  clients

** Technical Specification

   Currently a lot of operations are manual in WTD.  This has been
   largely intentional, as I've been trying to flesh out the
   interaction design of the system, and it is faster to prototype the
   interaction patterns manually than it would be writing code, that
   would end up being continually revised and discarded.  However, by
   now many interaction patterns are well-defined, so it's appropriate
   to automate them.

   In the current emacs lisp client code some functions are provided
   to do things like create journal entries in the transaction
   journal, and create internal links to the transactions for use in
   the index. We will incorporate http requests to the wtd server into
   the emacs client code as well.

   Probably the most obvious piece to implement is instruments.  For
   now it makes sense to simply define the instruments in the server
   code, though later a more modular design for adding instruments to
   the server for specific WTD setups could make sense.  For now, for
   simplicity's sake we will implement a pull-only model for
   instruments.  It remains to be seen whether a push approach will be
   useful, but if so it could be done via integration with redis
   streams on the server side, and websocket connection from emacs to
   the server.

** Usage

   TODO

** License

Copyright © 2020 FIXME

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.
